[Reptilien]
_color = [50, 150, 50]
_icon = "icons/reptiles.png"

[Reptilien.Mochi]
_icon = "icons/mochi.jpeg"
_art = "Kornnatter"

[Reptilien.Noodle]
_icon = "icons/noodle.jpeg"
_art = "Kornnatter"

[Reptilien.Popcorn]
_icon = "icons/popcorn.jpeg"
_art = "Kornnatter"

[Reptilien.Bibble]
_icon = "icons/bibble.jpeg"
_art = "Hakennasennatter"

[Reptilien.Mu-Shu]
_icon = "icons/mushu.jpeg"
_art = "Gargoylegecko"

[Reptilien.Ichigo]
_icon = "icons/ichigo.jpeg"
_art = "Gargoylegecko"
